
// Objective-C API for talking to the following Go packages
//
//	l2app/l2library/sdk/l2mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __L2mobile_FRAMEWORK_H__
#define __L2mobile_FRAMEWORK_H__

#include "L2mobile.objc.h"
#include "Universe.objc.h"

#endif
