// Objective-C API for talking to l2app/l2library/sdk/l2mobile Go package.
//   gobind -lang=objc l2app/l2library/sdk/l2mobile
//
// File is generated by gobind. Do not edit.

#ifndef __L2mobile_H__
#define __L2mobile_H__

@import Foundation;
#include "Universe.objc.h"


@class L2mobileL2;
@class L2mobileSession;
@protocol L2mobileCallback;
@class L2mobileCallback;
@protocol L2mobileSignHandler;
@class L2mobileSignHandler;

@protocol L2mobileCallback <NSObject>
- (void)onResult:(NSString*)err info:(NSString*)info;
@end

@protocol L2mobileSignHandler <NSObject>
- (void)sendTx:(NSString*)tx callback:(id<L2mobileCallback>)callback;
- (void)signMsg:(NSString*)msg callback:(id<L2mobileCallback>)callback;
@end

/**
 * 客户端数据定义 结构化
 */
@interface L2mobileL2 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (BOOL)call:(NSString*)command body:(NSString*)body callback:(id<L2mobileCallback>)callback error:(NSError**)error;
- (BOOL)initL2SDK:(NSString*)cpKey dataPath:(NSString*)dataPath address:(NSString*)address socketUrl:(NSString*)socketUrl signHandler:(id<L2mobileSignHandler>)signHandler error:(NSError**)error;
@end

@interface L2mobileSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)sessionId;
- (void)setSessionId:(NSString*)v;
- (NSString*)status;
- (void)setStatus:(NSString*)v;
@end

@class L2mobileCallback;

@class L2mobileSignHandler;

/**
 * 回调数据接口
 */
@interface L2mobileCallback : NSObject <goSeqRefInterface, L2mobileCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onResult:(NSString*)err info:(NSString*)info;
@end

/**
 * 外部传入的签名接口
 */
@interface L2mobileSignHandler : NSObject <goSeqRefInterface, L2mobileSignHandler> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)sendTx:(NSString*)tx callback:(id<L2mobileCallback>)callback;
- (void)signMsg:(NSString*)msg callback:(id<L2mobileCallback>)callback;
@end

#endif
