// Objective-C API for talking to L2Library/sdk/client Go package.
//   gobind -lang=objc L2Library/sdk/client
//
// File is generated by gobind. Do not edit.

#ifndef __Client_H__
#define __Client_H__

@import Foundation;
#include "Universe.objc.h"


@class ClientL2;

/**
 * 客户端数据定义 结构化
 */
@interface ClientL2 : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)address;
- (void)setAddress:(NSString*)v;
// skipped field L2.Socket with unsupported type: *golang.org/x/net/websocket.Conn

// skipped field L2.SendTxFunc with unsupported type: func(tx string, callback func(err error, txHash string))

// skipped field L2.SignMsgFunc with unsupported type: func(msg string, callback func(err error, signature string))

// skipped field L2.PnAddress with unsupported type: map[string]bool

// skipped field L2.BlockChain with unsupported type: *Vincent/golang/blockchain.Blockchain

// skipped field L2.EthContract with unsupported type: *Vincent/golang/contract.Ethchannel

/**
 * *
 * 添加支付网络
 *
 * @param pnAddress	string 		Payment Network Address
 *
 * @return bool 	true|false	操作结果
 *
 */
- (BOOL)addPN:(NSString*)pnAddress;
/**
 * *
 * 向通道中添加代币
 *
 * @param pnAddress string		Payment Network Address
 * @param amount 	string 		代币数量 (充值币种为支付合约绑定的币种)
 *
 * @returns bool 	true|false	操作结果
 */
- (BOOL)deposit:(NSString*)pnAddress amount:(NSString*)amount;
/**
 * *
 * 查询用户信息
 *
 * @param	pnAddress	string
 *
 * @return Payment Network List 支付网络列表
 */
- (void)queryPN;
/**
 * *
 * 查询用户信息
 *
 * @param	pnAddress	string	Payment Network Address
 *
 * @return 交易信息
 */
- (void)queryTransaction:(NSString*)pnAddress;
/**
 * *
 * 查询用户信息
 *
 * @param	pnAddress	string	Payment Network Address
 *
 * @return 用户信息
 */
- (void)queryUserInfo:(NSString*)pnAddress;
/**
 * *
 * 发送消息 (通过Socket， 向另一方发送消息)
 *
 * @param
 *
 * @return bool true|false 操作结果
 */
- (BOOL)sendMessage;
/**
 * *
 * 从通道中取出代币
 *
 * @param	pnAddress	string	Payment Network Address
 * @param	amount		int		代币数量 (取出币种为支付合约绑定的币种)
 *
 * @returns	bool	true|false	操作结果
 *
 * @description	当amount为通道的所有金额时, 通道会自动关闭。(协商关)
 */
- (BOOL)withdraw:(NSString*)pnAddress amount:(long)amount;
@end

// skipped function InitL2SDK with unsupported parameter or return types


#endif
